CREATE TABLE IF NOT EXISTS interactions(
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                           user_id BIGINT NOT NULL,
                                           rating DOUBLE NOT NULL,
                                           ts TIMESTAMP WITH TIME ZONE NOT NULL,
                                           UNIQUE (user_id, event_id)
    );

CREATE TABLE IF NOT EXISTS similarities (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                            eventA BIGINT NOT NULL,
                                            eventB BIGINT NOT NULL,
                                            similarity DOUBLE NOT NULL,
                                            ts TIMESTAMP WITH TIME ZONE NOT NULL,
                                            UNIQUE (eventA, eventB)
    );